### ISSUE TITLE
Unable to build under windows - error at test:bin task

### ISSUE THREAD

**Issue by blikblum** [wycats/handlebars.js#1233]
Cloned handlebars.js repository under windows 10 64bit, node 4.2.1

Installed dependencies `npm install`

Ran `grunt`. Initially there was an error in jison. After changing the eol of handlebars.I to unix it worked.

Again ran `grunt`

Got the following error:
Running "test:bin" task
Fatal error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "./bin/handlebars -a spec/artifacts/empty.handlebars"

To run ./bin/handlebars file under windows is necessary to execute `node ./bin/handlebars`

**Comment by kpdecker** [comment]
I don't have a windows box to test on, but if you submit a PR that fixes that issue, glad to accept.

**Comment by stevenvachon** [comment]
Test with [AppVeyor CI](https://appveyor.com).

**Comment by blikblum** [comment]
Done in https://github.com/wycats/handlebars.js/pull/1244

There still a issue with istanbul i could not find how to fix

**Comment by nknapp** [comment]
#1346 should fix this

**Comment by blikblum** [comment]
Hi updated and still getting an error:

```
Running "test:cov" task
D:\repositories\handlebars.js\node_modules\.bin\istanbul:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Fatal error: 1 tests failed
```
There's a `istanbul.cmd` file in .bin folder but is executing the `istanbul` bash script instead file.

I change to call `istanbul.cmd` but gives another error: 

```
D:\repositories\handlebars.js\node_modules\.bin\istanbul.cmd:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\n
ode.exe" (
```

Since fork is for a node.js module i tried spawn also without luck

Using node 6.9.1, windows 10

**Comment by nknapp** [comment]
Have you tried what you wrote and *then* notice that the PR was not merged yet? Or did the PR-commit not work either?

I have merged the PR now, so maybe you could try again.

**Comment by blikblum** [comment]
The mentioned issues were before merging. I tried the PR but got eslint errors. Will try after the merge

**Comment by blikblum** [comment]
I manually applied the changes to master branch and worked fine. I can do a PR if necessary.

The 4.x build failed with an error in jison but this is another issue

**Comment by nknapp** [comment]
I thought I pushed the merge to master already. No need to do a PR. I regularly merge from 4.x to master.

Is the jison error related to line endings? May there need to be more entries in .gitattributes 



Am 14. Mai 2017 17:41:16 MESZ schrieb "Luiz Américo" <notifications@github.com>:
>I manually applied the changes to master branch and worked fine. I can
>do a PR if necessary.
>
>The 4.x build failed with an error in jison but this is another issue
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/wycats/handlebars.js/issues/1233#issuecomment-301320948

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by blikblum** [comment]
> Is the jison error related to line endings?

No: 

```
Running "parser" task
D:\repositories\handlebars.js\node_modules\jison\lib\jison\util\lex-parser.js:13
3
    throw new Error(str);
    ^

Error: Parse error on line 2:
function strip(raw
---------------------^
Expecting '%%', 'ACTION', 'NAME', 'START_INC', 'START_EXC', 'START_COND', got '{
'
```

**Comment by nknapp** [comment]
@blikblum After changing the eol of handlebars.I to unix it worked. (That is what you found out about a year ago. A year can be a very long time, I know that.) 

I have added a .gitattributes-entry to fix that on Windows. Deletion and `git reset --hard' may be necessary to apply the changed line-endings.

**Comment by nknapp** [comment]
About the original issue: It still exists, but I'll integrate your suggestion, maybe slightly different, because on Linux it would still be good to call the script without the "node "-prefix

**Comment by nknapp** [comment]
I have created b

**Comment by nknapp** [comment]
Released in 4.0.11
